import { signInFormSchema } from "@/lib/form-schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { Metadata } from "next";
import React, { FC } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

interface SignInPageProps {}

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const SignInPage: FC<SignInPageProps> = ({}) => {
  const form = useForm<z.infer<typeof signInFormSchema>>({
    resolver: zodResolver(signInFormSchema),
  });

  const onSubmit = (val: z.infer<typeof signInFormSchema>) => {
    console.log(val);
  };

  return (
    <div className="relative w-full h-screen">
      <div className="absolute top-1/2 left-1/2 translate-x-1/2 translate-y-1/2">
        <div className="border border-border p-5">
          <div className="font-semibold text-center text-2xl mb-2">
            Login your account
          </div>
          <div className="text-sm text-gray-500">Enter your email</div>
        </div>
      </div>
    </div>
  );
};

export default SignInPage;
