import { signInFormSchema } from "@/lib/form-schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { Metadata } from "next";
import React, { FC } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

interface SignInPageProps {}

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const SignInPage: FC<SignInPageProps> = ({}) => {
  const form = useForm<z.infer<typeof signInFormSchema>>({
    resolver: zodResolver(signInFormSchema),
  });

  const onSubmit = (val: z.infer<typeof signInFormSchema>) => {
    console.log(val);
  };

  return <div></div>;
};

export default SignInPage;
